//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueRec
    {
        public short ValueID { get; set; }
        public short DeviceID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int RecordedVal { get; set; }
        public string Username { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
